//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public System.Guid ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public bool Eliminado { get; set; }
        public System.DateTime ModificadoEn { get; set; }
    }
}
