//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBiddingsDet
    {
        public System.Guid IdBiddingsDet { get; set; }
        public System.Guid IdBiddingsEnc { get; set; }
        public System.Guid IdProveedor { get; set; }
        public string FolioCotizacionProveedor { get; set; }
        public string Concepto { get; set; }
        public decimal CostoCotizacion { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public int Estatus { get; set; }
    }
}
