//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBiddingsEnc
    {
        public System.Guid IdBiddings { get; set; }
        public string FolioBiddings { get; set; }
        public string Concepto { get; set; }
        public string Planta { get; set; }
        public System.Guid IdArea { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.Guid IdUsuarioModificacion { get; set; }
        public int Estatus { get; set; }
        public Nullable<System.Guid> IdSolicitudCotizacion { get; set; }
        public string FolioCotizacion { get; set; }
        public string Comentarios { get; set; }
    }
}
