//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCajaChicaSucursal
    {
        public System.Guid IdCajaChicaSucursal { get; set; }
        public System.Guid IdSucursal { get; set; }
        public string Sucursal { get; set; }
        public string Concepto { get; set; }
        public decimal Cargo { get; set; }
        public decimal Abono { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int Estatus { get; set; }
        public string NombreArchivo { get; set; }
        public string Archivo { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.Guid IdUsuarioModifica { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.Guid IdCajaChica { get; set; }
    }
}
