//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCajaChicaSucursalDetalle
    {
        public System.Guid IdCajaChicaSucursalDetalle { get; set; }
        public System.Guid IdCajaChicaSucursal { get; set; }
        public System.Guid IdProyecto { get; set; }
        public string Concepto { get; set; }
        public decimal CantidadGastada { get; set; }
        public string TipoGasto { get; set; }
        public System.DateTime FechaGasto { get; set; }
        public string Ticket { get; set; }
        public int Estatus { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioModifica { get; set; }
        public System.DateTime FechaModifica { get; set; }
    }
}
