//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCajaChicaUSA
    {
        public System.Guid IdCajaChicaUsa { get; set; }
        public string Responsable { get; set; }
        public string Concepto { get; set; }
        public string IdProyecto { get; set; }
        public string Proyecto { get; set; }
        public string Comprobante { get; set; }
        public decimal Cargo { get; set; }
        public decimal Abono { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string Categoria { get; set; }
        public string CampoExtra { get; set; }
        public string FolioOrdenCompra { get; set; }
        public string NombreArchivo { get; set; }
        public string Archivo { get; set; }
        public Nullable<System.Guid> IdUsuarioAlta { get; set; }
        public Nullable<System.Guid> IdUsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
