//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClienteContacto
    {
        public System.Guid idContacto { get; set; }
        public System.Guid idEmpresa { get; set; }
        public string NombreContacto { get; set; }
        public string Telefono { get; set; }
        public string Foto { get; set; }
        public string Correo { get; set; }
        public string TIMESTAMP { get; set; }
        public bool Estatus { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public string Imagen { get; set; }
        public string NombreImagen { get; set; }
        public Nullable<System.Guid> IdArea { get; set; }
    }
}
