//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChat
    {
        public int IdChat { get; set; }
        public string IdFrom { get; set; }
        public string From { get; set; }
        public string IdTo { get; set; }
        public string To { get; set; }
        public string Message { get; set; }
        public System.DateTime MessageDate { get; set; }
        public int Leido { get; set; }
    }
}
