//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCotizacionesDet
    {
        public System.Guid idCotDetalle { get; set; }
        public Nullable<System.Guid> idCotizacion { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Unidad { get; set; }
        public Nullable<System.Guid> idUsuarioAlta { get; set; }
        public Nullable<int> Estatus { get; set; }
    }
}
