//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCotizacionNew
    {
        public System.Guid IdCotizacion { get; set; }
        public string NoCotizacion { get; set; }
        public System.Guid IdCliente { get; set; }
        public string Empresa { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Concepto { get; set; }
        public string FechaCotizacion { get; set; }
        public System.Guid IdUsuarioElaboro { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string Estatus { get; set; }
        public string NombreArchivoPdf { get; set; }
        public string DocumentoPdf { get; set; }
        public string NombreArchivoXls { get; set; }
        public string DocumentoXls { get; set; }
        public Nullable<decimal> CostoCotizacion { get; set; }
        public Nullable<System.Guid> IdUsuarioCancela { get; set; }
        public string ComentarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public Nullable<System.DateTime> FechaEnviada { get; set; }
        public Nullable<System.Guid> IdUsuarioEnvia { get; set; }
        public Nullable<System.Guid> IdUsuarioCreo { get; set; }
    }
}
