//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCostoIndirectoGlobal
    {
        public System.Guid IdCostoIndirectoGlobal { get; set; }
        public int Semana { get; set; }
        public decimal NominaGlobal { get; set; }
        public decimal ImssGlobal { get; set; }
        public decimal TotalGlobal { get; set; }
        public decimal TotalEmpleadosGlobal { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.Guid IdUsuarioModifica { get; set; }
        public Nullable<decimal> InteresGlobal { get; set; }
        public Nullable<decimal> TotalProyectos { get; set; }
        public Nullable<decimal> TotalCotizado { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<System.DateTime> FechaIni { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<decimal> Vacaciones { get; set; }
        public Nullable<decimal> Aguinaldo { get; set; }
    }
}
