//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatosEmpresa
    {
        public System.Guid IdDatos { get; set; }
        public decimal TipoCambio { get; set; }
        public decimal IvaFrontera { get; set; }
        public decimal IvaInterior { get; set; }
    }
}
