//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpresas
    {
        public System.Guid idEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string DireccionFiscal { get; set; }
        public string Telefono { get; set; }
        public System.DateTime TIMESTAMP { get; set; }
        public string RFC { get; set; }
        public string Correo { get; set; }
        public int CP { get; set; }
        public string Ciudad { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.Guid> idSucursalRegistro { get; set; }
        public string Cliente { get; set; }
    }
}
