//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEficiencias
    {
        public int idEficiencia { get; set; }
        public Nullable<System.Guid> idProyecto { get; set; }
        public Nullable<decimal> ManoObra { get; set; }
        public Nullable<decimal> Material { get; set; }
        public Nullable<decimal> Equipo { get; set; }
    }
}
