//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEficienciasDesglose
    {
        public int idEficiencia { get; set; }
        public string idProyecto { get; set; }
        public string idDocumento { get; set; }
        public string Categoria { get; set; }
        public string TipoDoc { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> FechaDoc { get; set; }
        public string idUsuarioUltimo { get; set; }
    }
}
