//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFolioOrdenCompra
    {
        public System.Guid IdFolioOrdenCompra { get; set; }
        public System.DateTime Dia { get; set; }
        public Nullable<int> Consecutivo { get; set; }
    }
}
