//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFacturasEmitidas
    {
        public System.Guid IdFacturasEmitidas { get; set; }
        public string FolioFactura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public string RfcReceptor { get; set; }
        public string NombreReceptor { get; set; }
        public string IdProyecto { get; set; }
        public string NoCotizacion { get; set; }
        public string OrdenCompraRecibida { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Iva { get; set; }
        public decimal Total { get; set; }
        public string Moneda { get; set; }
        public Nullable<System.DateTime> ProgramacionPago { get; set; }
        public Nullable<decimal> PorPagar { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public int Estatus { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<decimal> Retencion { get; set; }
        public string NombreArchivo { get; set; }
        public string ArchivoPDF { get; set; }
        public Nullable<int> Enviada { get; set; }
        public string CorreoEnviado { get; set; }
        public Nullable<System.DateTime> FechaPA { get; set; }
    }
}
