//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGastos
    {
        public System.Guid IdGasto { get; set; }
        public System.Guid IdProyecto { get; set; }
        public string NoFactura { get; set; }
        public string TipoGasto { get; set; }
        public string Descripcion { get; set; }
        public decimal Importe { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public System.DateTime FechaGasto { get; set; }
        public System.Guid IdUsuario { get; set; }
        public System.DateTime FechaAlta { get; set; }
    }
}
