//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGPS
    {
        public int IdLocation { get; set; }
        public string ID { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
