//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHorasHombre
    {
        public System.Guid IdHorasHombre { get; set; }
        public System.Guid IdProyecto { get; set; }
        public System.Guid IdUsuario { get; set; }
        public decimal Lunes { get; set; }
        public decimal Martes { get; set; }
        public decimal Miercoles { get; set; }
        public decimal Jueves { get; set; }
        public decimal Viernes { get; set; }
        public decimal Sabado { get; set; }
        public decimal Domingo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int Activo { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
    }
}
