//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHabilidades
    {
        public System.Guid IdHabilidad { get; set; }
        public System.Guid IdUsuario { get; set; }
        public string Habilidad { get; set; }
        public decimal Porcentaje { get; set; }
        public string Comentarios { get; set; }
    }
}
