//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventarioDet
    {
        public int idHDet { get; set; }
        public Nullable<int> idHerramienta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Entrada { get; set; }
        public Nullable<decimal> Salida { get; set; }
        public Nullable<System.Guid> idUsuario { get; set; }
    }
}
