//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblListaPendientes
    {
        public System.Guid IdListaPendientes { get; set; }
        public System.Guid IdUsuario { get; set; }
        public string Pendiente { get; set; }
        public int Completado { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.DateTime FechaCompletado { get; set; }
    }
}
