//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModuloPO
    {
        public System.Guid IdModuloPO { get; set; }
        public System.DateTime Fecha { get; set; }
        public string FolioPO { get; set; }
        public int MarkUP { get; set; }
        public System.Guid IdCliente { get; set; }
        public string Contacto { get; set; }
        public string Comprador { get; set; }
        public string NoCotizacion { get; set; }
        public decimal Monto { get; set; }
        public System.Guid IdMoneda { get; set; }
        public string Estatus { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.Guid IdUsuarioModificacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaEliminado { get; set; }
        public Nullable<System.Guid> IdUsuarioEliminado { get; set; }
        public Nullable<System.Guid> IdSucursal { get; set; }
    }
}
