//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public int IdMenu { get; set; }
        public System.Guid Identificador { get; set; }
        public string Seccion { get; set; }
        public string Icono { get; set; }
        public string Menu { get; set; }
        public string Accion { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Pagina { get; set; }
    }
}
