//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatrizMecanico
    {
        public System.Guid IdMaquinado { get; set; }
        public System.Guid IdProyecto { get; set; }
        public string NombreProyecto { get; set; }
        public string NoParte { get; set; }
        public System.DateTime FechaOC { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public Nullable<System.Guid> IdDiseno { get; set; }
        public Nullable<System.Guid> IdMasterCam { get; set; }
        public int Estatus { get; set; }
        public System.Guid IdEncargadoProyecto { get; set; }
        public System.Guid IdDisenador { get; set; }
        public System.Guid IdQuienHizo { get; set; }
        public string Observaciones { get; set; }
        public int HorasMaquina { get; set; }
        public int CantidadPzas { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
    }
}
