//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrdenCompraInsumos
    {
        public System.Guid IdOrdenCompra { get; set; }
        public string Folio { get; set; }
        public System.Guid IdProveedor { get; set; }
        public string ReferenciaCot { get; set; }
        public string IdProyecto { get; set; }
        public System.Guid IdUsuario { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Iva { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int Estatus { get; set; }
        public int Enviada { get; set; }
        public string EnviarA { get; set; }
        public System.Guid IdMoneda { get; set; }
        public string CondicionPago { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.Guid IdUsuarioCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.Guid IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string IdUsuarioCancelacion { get; set; }
        public string MotivoCancelacion { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<System.Guid> IdUsuarioAprobo { get; set; }
        public Nullable<System.Guid> idSucursal { get; set; }
        public string FolioReq { get; set; }
        public string NombreCotProv1 { get; set; }
        public string ArchivoCotProv1 { get; set; }
        public string IdProveedorCot1 { get; set; }
        public Nullable<decimal> MontoCotProv1 { get; set; }
        public string UsuarioCotProv1 { get; set; }
        public Nullable<System.DateTime> FechaCotProv1 { get; set; }
        public string NombreCotProv2 { get; set; }
        public string ArchivoCotProv2 { get; set; }
        public string IdProveedorCot2 { get; set; }
        public Nullable<decimal> MontoCotProv2 { get; set; }
        public string UsuarioCotProv2 { get; set; }
        public Nullable<System.DateTime> FechaCotProv2 { get; set; }
        public string NombreCotProv3 { get; set; }
        public string ArchivoCotProv3 { get; set; }
        public string IdProveedorCot3 { get; set; }
        public Nullable<decimal> MontoCotProv3 { get; set; }
        public string UsuarioCotProv3 { get; set; }
        public Nullable<System.DateTime> FechaCotProv3 { get; set; }
        public Nullable<System.Guid> IdCriterio { get; set; }
    }
}
