//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrdenCompraCambios
    {
        public System.Guid IdOrdenCompraModificada { get; set; }
        public System.Guid IdUsuarioModifica { get; set; }
        public string Modificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.Guid IdOrdenCompra { get; set; }
    }
}
