//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrdenCompraNota
    {
        public System.Guid IdOrdenCompraNota { get; set; }
        public System.Guid IdOdenCompra { get; set; }
        public int Item { get; set; }
        public string NotaAclaratoria { get; set; }
    }
}
