//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrdenCompraArchivos
    {
        public System.Guid IdArchivoCotOC { get; set; }
        public System.Guid IdOrdenCompra { get; set; }
        public string NombreArchivo { get; set; }
        public string FileExtension { get; set; }
        public string FileSize { get; set; }
        public string FileContentType { get; set; }
        public string Archivo { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.Guid IdUsuario { get; set; }
    }
}
