//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProveedores
    {
        public System.Guid IdProveedor { get; set; }
        public string Proveedor { get; set; }
        public string Contacto { get; set; }
        public string Domicilio { get; set; }
        public string Coordenadas { get; set; }
        public string Email { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Giro { get; set; }
        public string Comentarios { get; set; }
        public string Imagen { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.Guid IdUsuarioModifica { get; set; }
        public int Activo { get; set; }
        public string NombreComercial { get; set; }
        public Nullable<int> DiasCredito { get; set; }
        public Nullable<System.Guid> idSucursal { get; set; }
        public string RFC { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public Nullable<decimal> CapFinanciera { get; set; }
        public string PerfilEmpresa { get; set; }
    }
}
