//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaqueteEnc_CCM
    {
        public System.Guid IdPaqueteEnc { get; set; }
        public string Folio { get; set; }
        public System.Guid IdCliente { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<System.Guid> IdUsuarioDescuento { get; set; }
        public Nullable<System.DateTime> FechaDescuento { get; set; }
        public Nullable<System.Guid> IdClienteModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
