//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPagosFacturasOrdenes
    {
        public System.Guid IdPago { get; set; }
        public System.Guid IdOrdenCompra { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Pago { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public Nullable<System.Guid> IdBanco { get; set; }
        public string FolioFactura { get; set; }
    }
}
