//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProyectosProyFinanciera
    {
        public System.Guid IdProyeccionFinanciera { get; set; }
        public System.Guid IdProyecto { get; set; }
        public decimal str10 { get; set; }
        public decimal str20 { get; set; }
        public decimal str30 { get; set; }
        public decimal str40 { get; set; }
        public decimal str50 { get; set; }
        public decimal str60 { get; set; }
        public decimal str70 { get; set; }
        public decimal str80 { get; set; }
        public decimal str90 { get; set; }
        public decimal str100 { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.Guid IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> strFecha10 { get; set; }
        public Nullable<System.DateTime> strFecha20 { get; set; }
        public Nullable<System.DateTime> strFecha30 { get; set; }
        public Nullable<System.DateTime> strFecha40 { get; set; }
        public Nullable<System.DateTime> strFecha50 { get; set; }
        public Nullable<System.DateTime> strFecha60 { get; set; }
        public Nullable<System.DateTime> strFecha70 { get; set; }
        public Nullable<System.DateTime> strFecha80 { get; set; }
        public Nullable<System.DateTime> strFecha90 { get; set; }
        public Nullable<System.DateTime> strFecha100 { get; set; }
    }
}
