//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProyectosBK
    {
        public int IdProyecto { get; set; }
        public System.Guid ID { get; set; }
        public string NombreProyecto { get; set; }
        public string Descripcion { get; set; }
        public System.Guid IdLider { get; set; }
        public Nullable<System.Guid> IdCliente { get; set; }
        public string Estatus { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int Activo { get; set; }
        public Nullable<System.Guid> UserProject1 { get; set; }
        public Nullable<System.Guid> UserProject2 { get; set; }
        public Nullable<System.Guid> UserProject3 { get; set; }
        public Nullable<System.Guid> UserProject4 { get; set; }
        public Nullable<System.Guid> IdCotizacion { get; set; }
        public Nullable<decimal> CostoCotizacion { get; set; }
    }
}
