//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProveedorMaterial
    {
        public System.Guid IdProveedorMaterial { get; set; }
        public System.Guid IdProveedor { get; set; }
        public System.Guid IdMaterial { get; set; }
        public string UnidadMedida { get; set; }
        public decimal Precio { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public System.Guid IdMoneda { get; set; }
        public int Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.Guid IdUsuarioModificacion { get; set; }
    }
}
