//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRolesContactos
    {
        public System.Guid IdRolContacto { get; set; }
        public System.Guid IdContacto { get; set; }
        public string Tipo { get; set; }
        public int Cotizaciones { get; set; }
        public int CotizacionesAgregar { get; set; }
        public int CotizacionesEditar { get; set; }
        public int CotizacionesEliminar { get; set; }
        public int Proyectos { get; set; }
        public int Paquetes { get; set; }
        public int PaquetesAgregar { get; set; }
        public int PaquetesEditar { get; set; }
        public int PaquetesEliminar { get; set; }
        public int ActivaSitio { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioModifica { get; set; }
        public System.DateTime FechaModifica { get; set; }
        public int Biddings { get; set; }
        public int BiddingsAgregar { get; set; }
        public int BiddingsEditar { get; set; }
        public int BiddingsEliminar { get; set; }
    }
}
