//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRolesUsuarios
    {
        public System.Guid idRol { get; set; }
        public string Tipo { get; set; }
        public System.Guid idUsuarios { get; set; }
        public bool ClienteEmpresa { get; set; }
        public bool ClienteEmpresaAgregar { get; set; }
        public bool ClienteEmpresaEditar { get; set; }
        public bool ClienteEmpresaEliminar { get; set; }
        public bool ClienteContacto { get; set; }
        public bool ClienteContactoAgrear { get; set; }
        public bool ClienteContactoEditar { get; set; }
        public bool ClienteContactoEliminar { get; set; }
        public bool RFQ { get; set; }
        public bool RFQAgregar { get; set; }
        public bool RFQEditar { get; set; }
        public bool RFQEliminar { get; set; }
        public bool Cotizaciones { get; set; }
        public bool CotizacionesAgregar { get; set; }
        public bool CotizacionesEditar { get; set; }
        public bool CotizacionesEliminar { get; set; }
        public bool Materiales { get; set; }
        public bool MaterialesAgregar { get; set; }
        public bool MaterialesEditar { get; set; }
        public bool MaterialesEliminar { get; set; }
        public bool Proveedores { get; set; }
        public bool ProveedoresAgregar { get; set; }
        public bool ProveedoresEditar { get; set; }
        public bool ProveedoresEliminar { get; set; }
        public bool Requisiciones { get; set; }
        public bool RequisicionesAgregar { get; set; }
        public bool RequisicionesEditar { get; set; }
        public bool RequisicionesEliminar { get; set; }
        public bool OC { get; set; }
        public bool OCAgregar { get; set; }
        public bool OCEditar { get; set; }
        public bool OCEliminar { get; set; }
        public bool Viaticos { get; set; }
        public bool ViaticosAgregar { get; set; }
        public bool ViaticosEditar { get; set; }
        public bool ViaticosEliminar { get; set; }
        public bool Proyectos { get; set; }
        public bool ProyectosEditar { get; set; }
        public bool ProyectosEliminar { get; set; }
        public bool ProyectosAgregar { get; set; }
        public bool CajaChica { get; set; }
        public bool CajaChicaAgregar { get; set; }
        public bool CajaChicaEditar { get; set; }
        public bool CajaChicaEliminar { get; set; }
        public bool Usuarios { get; set; }
        public bool UsuariosAgregar { get; set; }
        public bool UsuariosEditar { get; set; }
        public bool UsuariosEliminar { get; set; }
        public bool Sucursales { get; set; }
        public bool SucursalesAgregar { get; set; }
        public bool SucursalesEditar { get; set; }
        public bool SucursalesEliminar { get; set; }
        public bool ControlFacturas { get; set; }
        public bool ControlDocumentos { get; set; }
        public bool Administracion { get; set; }
        public bool Timming { get; set; }
        public Nullable<bool> Boletines { get; set; }
        public bool ServiciosCarro { get; set; }
        public bool Inventario { get; set; }
        public bool ServiciosComputo { get; set; }
        public Nullable<bool> FacturasEmitidas { get; set; }
        public Nullable<bool> Reportes { get; set; }
        public Nullable<bool> rptOrdenCompra { get; set; }
        public Nullable<bool> rptFacturasRecibidas { get; set; }
        public Nullable<bool> rptFacturasEmitidas { get; set; }
        public Nullable<bool> rptProyectos { get; set; }
        public Nullable<bool> rptCotizaciones { get; set; }
        public Nullable<bool> rptProyectosGastos { get; set; }
        public Nullable<bool> rptProveedoresPagar { get; set; }
        public bool FacRecibidas { get; set; }
        public Nullable<bool> FacRecibidasAgregar { get; set; }
        public Nullable<bool> FacRecibidasEditar { get; set; }
        public Nullable<bool> FacRecibidasEliminar { get; set; }
        public bool FacEmitidas { get; set; }
        public Nullable<bool> FacEmitidasAgregar { get; set; }
        public Nullable<bool> FacEmitidasEditar { get; set; }
        public Nullable<bool> FacEmitidasEliminar { get; set; }
        public Nullable<bool> rptEficiencias { get; set; }
        public bool Savings { get; set; }
        public Nullable<bool> ModuloPO { get; set; }
        public Nullable<bool> CostoIndirecto { get; set; }
        public Nullable<bool> CajaChicaSucursal { get; set; }
        public Nullable<bool> CajaChicaSucursalAgregar { get; set; }
        public Nullable<bool> CajaChicaSucursalEditar { get; set; }
        public Nullable<bool> CajaChicaSucursalEliminar { get; set; }
        public Nullable<bool> rptMonitor { get; set; }
        public Nullable<bool> CajaChicaCuautitlan { get; set; }
        public Nullable<bool> CajaChicaChihuahua { get; set; }
        public Nullable<bool> CajaChicaUSA { get; set; }
        public Nullable<bool> CajaChicaIrapuato { get; set; }
        public Nullable<bool> CajaChicaQueretaro { get; set; }
        public Nullable<bool> CajaChicaTecate { get; set; }
    }
}
