//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRFQ
    {
        public System.Guid IdRfq { get; set; }
        public string Folio { get; set; }
        public string Round { get; set; }
        public string Fecha { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public System.Guid IdCliente { get; set; }
        public string FolioRQ { get; set; }
        public System.Guid IdComprador { get; set; }
        public Nullable<System.Guid> IdCotizacion { get; set; }
        public string ArchivoRFQ { get; set; }
        public int Estatus { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioModificar { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.Guid> idVendedor { get; set; }
        public Nullable<System.Guid> idCoordinador { get; set; }
        public string Seguimiento { get; set; }
    }
}
