//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReqDet
    {
        public System.Guid IdReqDet { get; set; }
        public System.Guid IdReqEnc { get; set; }
        public int Item { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public string Unidad { get; set; }
        public string NumeroParte { get; set; }
        public string Marca { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
