//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRolesProveedores
    {
        public System.Guid IdRolProveedor { get; set; }
        public System.Guid IdProveedor { get; set; }
        public bool Biddings { get; set; }
        public bool BiddingsAgregar { get; set; }
        public bool BiddingsEditar { get; set; }
        public bool BiddingsEliminar { get; set; }
        public bool ActivaSitio { get; set; }
        public System.Guid IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioModifica { get; set; }
        public System.DateTime FechaModifica { get; set; }
    }
}
