//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitudesAprobacion
    {
        public int idSolicitud { get; set; }
        public string UsuarioSolicita { get; set; }
        public string idUsuarioSolicita { get; set; }
        public System.DateTime timestamp { get; set; }
        public bool Estatus { get; set; }
        public string CondicionEstatus { get; set; }
        public string Comentarios { get; set; }
        public System.Guid idDocumento { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.Guid> idUsuarioAprobo { get; set; }
        public string usuarioAprobo { get; set; }
    }
}
