//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitudCotizacion_CCM
    {
        public System.Guid idSolicitudCotizacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.Guid Requisitor { get; set; }
        public string NombreRequisitor { get; set; }
        public string CDSID { get; set; }
        public string Telefono { get; set; }
        public System.Guid idArea { get; set; }
        public string Resumen { get; set; }
        public System.DateTime FechaVisita { get; set; }
        public System.TimeSpan HoraVisita { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string UbicacionTrabajo { get; set; }
        public string Objetivo { get; set; }
        public string Folio { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<System.DateTime> FechaActualizaEntrega { get; set; }
        public Nullable<System.Guid> IdUsuarioPM { get; set; }
        public string PlantaCCM { get; set; }
        public string Tipo { get; set; }
        public string TipoCotizacion { get; set; }
        public string FolioTipo { get; set; }
    }
}
