//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSucursales
    {
        public System.Guid idSucursa { get; set; }
        public string CiudadSucursal { get; set; }
        public string DireccionSucursal { get; set; }
        public string TelefonoSucursal { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string Gerente { get; set; }
        public string ColoniaSucursal { get; set; }
        public string CPSucursal { get; set; }
    }
}
