//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeamProject
    {
        public System.Guid IdTeamProject { get; set; }
        public System.Guid IdProyecto { get; set; }
        public System.Guid IdUsuario { get; set; }
        public int EsLider { get; set; }
    }
}
