//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuarios
    {
        public System.Guid IdUsuario { get; set; }
        public string NombreCompleto { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string Foto { get; set; }
        public Nullable<int> Permisos { get; set; }
        public string Puesto { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<int> EsLiderProyecto { get; set; }
        public string Perfil { get; set; }
        public Nullable<decimal> SueldoDiario { get; set; }
        public Nullable<System.Guid> idSucursal { get; set; }
        public Nullable<int> EsCCM { get; set; }
        public string PuestoCCM { get; set; }
        public string AreaCCM { get; set; }
        public string PlantaCCM { get; set; }
    }
}
