//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblViaticos
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IdProyecto { get; set; }
        public decimal CantEntregada { get; set; }
        public decimal CantGastada { get; set; }
        public Nullable<decimal> Diferencia { get; set; }
        public System.Guid IdUsuario { get; set; }
        public Nullable<int> Estatus { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public string Concepto { get; set; }
        public string Comentarios { get; set; }
    }
}
