//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblViaticosDet
    {
        public System.Guid IdDet { get; set; }
        public System.Guid IdViaticos { get; set; }
        public System.DateTime FechaViaticos { get; set; }
        public decimal Gasolina { get; set; }
        public decimal Desayuno { get; set; }
        public decimal Comida { get; set; }
        public decimal Cena { get; set; }
        public decimal Casetas { get; set; }
        public decimal Hotel { get; set; }
        public decimal Transporte { get; set; }
        public decimal Otros { get; set; }
        public string Descripcion { get; set; }
        public string Ticket { get; set; }
        public Nullable<System.Guid> idProyecto { get; set; }
        public Nullable<decimal> ManoObra { get; set; }
        public Nullable<decimal> Equipo { get; set; }
        public Nullable<decimal> Materiales { get; set; }
    }
}
