//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehiculoServicio
    {
        public System.Guid IdServicioVehiculo { get; set; }
        public System.Guid IdCarro { get; set; }
        public int KilometrajeActual { get; set; }
        public string Taller { get; set; }
        public int KilometrajeProximo { get; set; }
        public System.DateTime FechaServicio { get; set; }
        public string TipoServicio { get; set; }
        public System.Guid IdUsuario { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid IdUsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    }
}
