//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilidadPastel
    {
        public string Nombre { get; set; }
        public Nullable<decimal> Dato { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public int idU { get; set; }
        public Nullable<decimal> DatoSinIva { get; set; }
        public Nullable<decimal> PorcentajeSinIva { get; set; }
    }
}
